apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-pusher-client.fullname" . }}
  labels:
    {{- include "nexus-pusher-client.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus-pusher-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nexus-pusher-client.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: {{ include "nexus-pusher-client.volume-name" . }}
            mountPath: "{{ .Values.configFile.path }}{{ .Values.configFile.name }}"
            subPath: {{ .Values.configFile.name }}
            readOnly: true
      volumes:
        - name: {{ include "nexus-pusher-client.volume-name" . }}
          secret:
            secretName: {{ include "nexus-pusher-client.fullname" . }}
