apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "nexus-pusher-client.labels" . | nindent 4 }}
  name: {{ include "nexus-pusher-client.fullname" . }}
type: Opaque
stringData:
  "{{ .Values.configFile.name }}": |-
    client:
      daemon:
        enabled: true
        syncEveryMinutes: {{ .Values.client.sync }}
      server: {{ required ".Values.client.server missing" .Values.client.server }}
      serverAuth:
        user: {{ required ".Values.client.serverAuth.user missing" .Values.client.serverAuth.user }}
        pass: {{ required ".Values.client.serverAuth.pass" .Values.client.serverAuth.pass }}
      syncConfigs: {{ required ".Values.client.syncConfigs missing" .Values.client.syncConfigs | b64dec | nindent 8 }}