################
# Build GO app #
################
FROM golang:1.17.10-alpine3.16 as builder

WORKDIR /app

RUN apk add --no-cache gcc=11.2.1_git20220219-r2 upx=3.96-r1 && \
    rm -rf /var/cache/apk/*

COPY go.* ./
RUN go mod download

COPY . ./

RUN chmod +x ./tests.sh && \
    ./tests.sh && \
    make docker_build && \
    upx --best --lzma nexus-pusher

#########################
# Get certs and TZ data #
#########################
FROM alpine:3.16 as certer
RUN apk --no-cache add ca-certificates tzdata && \
    rm -rf /var/cache/apk/*

####################
# Configure server #
####################
FROM alpine:3.16 as configurer
RUN  apk --no-cache add yq=4.25.1-r1 && \
     rm -rf /var/cache/apk/*

WORKDIR /app
COPY ci/server-config.yaml ./

ARG concurrency
ARG username
ARG password
ARG tls_enabled
ARG tls_autocert
ARG domainName

ENV CONCURRENCY=$concurrency
ENV USERNAME=$username
ENV PASSWORD=$password
ENV TLS_ENABLED=$tls_enabled
ENV TLS_AUTOCERT=$tls_autocert
ENV DOMAIN_NAME=$domainName

RUN yq e -i '.server.concurrency = env(CONCURRENCY)' server-config.yaml && \
    yq e -i '.server.tls.enabled = env(TLS_ENABLED)' server-config.yaml && \
    yq e -i '.server.tls.auto = env(TLS_AUTOCERT)' server-config.yaml && \
    yq e -i '.server.tls.domainName = env(DOMAIN_NAME)' server-config.yaml && \
    yq e -i '.server.credentials += { env(USERNAME):env(PASSWORD) }' server-config.yaml

################################################
# Use scratch image to reduce final image size #
################################################
FROM scratch

ENV TZ="Europe/Moscow"

COPY --from=certer /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=certer /usr/share/zoneinfo /usr/share/zoneinfo/

COPY --from=builder /app/nexus-pusher /app/nexus-pusher
COPY --from=configurer /app/server-config.yaml /app/server-config.yaml

WORKDIR /app
CMD ["./nexus-pusher", "-c", "server-config.yaml"]