################
# Build GO app #
################
FROM golang:1.17-buster as builder

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . ./

RUN chmod +x ./tests.sh
RUN ./tests.sh

RUN make docker_build

#########################
# Get certs and TZ data #
#########################
FROM alpine:latest as certer
RUN apk update && apk add ca-certificates tzdata

####################
# Configure server #
####################
FROM alpine:latest as configurer
RUN apk update && apk add yq

WORKDIR /app
COPY ci/server-config.yaml ./

ARG concurrency
ARG username
ARG password
ARG tls_enabled
ARG tls_autocert
ARG domainName

ENV CONCURRENCY=$concurrency
ENV USERNAME=$username
ENV PASSWORD=$password
ENV TLS_ENABLED=$tls_enabled
ENV TLS_AUTOCERT=$tls_autocert
ENV DOMAIN_NAME=$domainName

RUN yq e -i '.server.concurrency = env(CONCURRENCY)' server-config.yaml && \
    yq e -i '.server.tls.enabled = env(TLS_ENABLED)' server-config.yaml && \
    yq e -i '.server.tls.auto = env(TLS_AUTOCERT)' server-config.yaml && \
    yq e -i '.server.tls.domainName = env(DOMAIN_NAME)' server-config.yaml && \
    yq e -i '.server.credentials += { env(USERNAME):env(PASSWORD) }' server-config.yaml

################################################
# Use scratch image to reduce final image size #
################################################
FROM scratch

ENV TZ="Europe/Moscow"

COPY --from=certer /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=certer /usr/share/zoneinfo /usr/share/zoneinfo/

COPY --from=builder /app/nexus-pusher /app/nexus-pusher
COPY --from=configurer /app/server-config.yaml /app/server-config.yaml

WORKDIR /app
CMD ["./nexus-pusher", "-c", "server-config.yaml"]