################
# Build GO app #
################
FROM golang:1.17-buster as builder

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . ./

RUN chmod +x ./tests.sh
RUN ./tests.sh

RUN make docker_build

#########################
# Get certs and TZ data #
#########################
FROM alpine:latest as certer
RUN apk update && apk add ca-certificates tzdata

################################################
# Use scratch image to reduce final image size #
################################################
FROM scratch

ENV TZ="Europe/Moscow"

COPY --from=certer /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=certer /usr/share/zoneinfo /usr/share/zoneinfo/

COPY --from=builder /app/nexus-pusher /app/nexus-pusher

WORKDIR /app
CMD ["./nexus-pusher", "-c", "/app/client-config.yaml"]