name: Sever Build and Publish Prod

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.yml'

  workflow_dispatch:
    inputs:
      concurrency:
        description: Maximum allowed parallel jobs
        required: true
        default: "30"
      domainName:
        description: FQDN for server TLS domain
        required: false
        default: "www.mydomain.com"
      tls-enabled:
        type: boolean
        description: Enables TLS support
        required: true
        default: false
      tls-autocert:
        type: boolean
        description: Enables Let's encrypt auto cert issuing
        required: false
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        env:
          concurrency: 30
          tls-enabled: false
          tls-autocert: false
          domainName: ""
        with:
          context: .
          file: ci/Dockerfile-server
          tags: |
            rageofgods/nexus-pusher-server:latest
          build-args: |
            "concurrency=${{ github.event.inputs.concurrency || env.concurrency }}"
            "username=${{ secrets.SRV_USERNAME }}"
            "password=${{ secrets.SRV_PASSWORD }}"
            "tls_enabled=${{ github.event.inputs.tls-enabled || env.tls-enabled }}"
            "tls_autocert=${{ github.event.inputs.tls-autocert || env.tls-autocert }}"
            "domainName=${{ github.event.inputs.domainName || env.domainName }}"
          push: true